<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 5/17: create tag table
 */
final class Version20260901160005 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create tag table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE tag (
                id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(50)                         NOT NULL,
                PRIMARY KEY (id)
            )
        ');
        
        // Functional index: tag names are unique case-insensitively (Doctrine cannot express this).
        $this->addSql('
            CREATE UNIQUE INDEX uniq_tag_name_lower 
            ON tag (LOWER(name))
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX uniq_tag_name_lower');
        $this->addSql('DROP TABLE tag');
    }
}