<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 10/17: create cv table (depends on user, position)
 */
final class Version20260901160010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create cv table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE cv (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                status       VARCHAR(20)                          DEFAULT \'DRAFT\' NOT NULL,
                is_visible   BOOLEAN                              DEFAULT TRUE  NOT NULL,
                likes_count  INT                                  DEFAULT 0     NOT NULL,
                version      INT                                  DEFAULT 1     NOT NULL,
                created_at   TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                updated_at   TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                candidate_id INT                                  NOT NULL,
                position_id  INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX IDX_B66FFE9291BD8781 
            ON cv (candidate_id)
        ');

        $this->addSql('
            CREATE INDEX IDX_B66FFE92DD842E46 
            ON cv (position_id)
        ');

        $this->addSql('
            CREATE UNIQUE INDEX uniq_cv_candidate_position 
            ON cv (candidate_id, position_id)
        ');

        $this->addSql('
            ALTER TABLE cv 
            ADD CONSTRAINT FK_B66FFE9291BD8781 
            FOREIGN KEY (candidate_id) 
            REFERENCES "user" (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');

        $this->addSql('
            ALTER TABLE cv 
            ADD CONSTRAINT FK_B66FFE92DD842E46 
            FOREIGN KEY (position_id) 
            REFERENCES position (id) 
            ON DELETE RESTRICT 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE9291BD8781');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE92DD842E46');
        $this->addSql('DROP TABLE cv');
    }
}