<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 9/17: create candidate_attribute_value table (depends on candidate_profile, attribute, attribute_option)
 */
final class Version20260901160009 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create candidate_attribute_value table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE candidate_attribute_value (
                id                    INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                value_string          VARCHAR(255)                         DEFAULT NULL,
                value_text            TEXT                                 DEFAULT NULL,
                value_numeric         NUMERIC(12, 2)                       DEFAULT NULL,
                value_date            TIMESTAMP(0) WITHOUT TIME ZONE       DEFAULT NULL,
                value_date_range_start TIMESTAMP(0) WITHOUT TIME ZONE      DEFAULT NULL,
                value_date_range_end  TIMESTAMP(0) WITHOUT TIME ZONE       DEFAULT NULL,
                value_boolean         BOOLEAN                              DEFAULT NULL,
                version               INT                                  DEFAULT 1 NOT NULL,
                updated_at            TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                profile_id            INT                                  NOT NULL,
                attribute_id          INT                                  NOT NULL,
                value_option_id       INT                                  DEFAULT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX IDX_540006F7CCFA12B8 
            ON candidate_attribute_value (profile_id)
        ');

        $this->addSql('
            CREATE INDEX IDX_540006F7B6E62EFA 
            ON candidate_attribute_value (attribute_id)
        ');

        $this->addSql('
            CREATE INDEX IDX_540006F7E25618D9 
            ON candidate_attribute_value (value_option_id)
        ');

        $this->addSql('
            CREATE UNIQUE INDEX uniq_candidate_attribute_value_profile 
            ON candidate_attribute_value (profile_id, attribute_id)
        ');

        $this->addSql('
            ALTER TABLE candidate_attribute_value 
            ADD CONSTRAINT FK_540006F7CCFA12B8 
            FOREIGN KEY (profile_id) 
            REFERENCES candidate_profile (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');

        $this->addSql('
            ALTER TABLE candidate_attribute_value 
            ADD CONSTRAINT FK_540006F7B6E62EFA 
            FOREIGN KEY (attribute_id) 
            REFERENCES attribute (id) 
            ON DELETE RESTRICT 
            NOT DEFERRABLE
        ');

        $this->addSql('
            ALTER TABLE candidate_attribute_value 
            ADD CONSTRAINT FK_540006F7E25618D9 
            FOREIGN KEY (value_option_id) 
            REFERENCES attribute_option (id) 
            ON DELETE SET NULL 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE candidate_attribute_value DROP CONSTRAINT FK_540006F7CCFA12B8');
        $this->addSql('ALTER TABLE candidate_attribute_value DROP CONSTRAINT FK_540006F7B6E62EFA');
        $this->addSql('ALTER TABLE candidate_attribute_value DROP CONSTRAINT FK_540006F7E25618D9');
        $this->addSql('DROP TABLE candidate_attribute_value');
    }
}