<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260901165851 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, category VARCHAR(40) NOT NULL, data_type VARCHAR(40) NOT NULL, description TEXT DEFAULT NULL, is_built_in BOOLEAN DEFAULT false NOT NULL, is_active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FA7AEFFB5E237E06 ON attribute (name)');
        $this->addSql('CREATE TABLE attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, value VARCHAR(255) NOT NULL, sort_order INT DEFAULT 0 NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_attribute_option_attribute ON attribute_option (attribute_id)');
        $this->addSql('CREATE TABLE candidate_attribute_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value_string VARCHAR(255) DEFAULT NULL, value_text TEXT DEFAULT NULL, value_numeric NUMERIC(12, 2) DEFAULT NULL, value_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value_date_range_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value_date_range_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, value_boolean BOOLEAN DEFAULT NULL, version INT DEFAULT 1 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, profile_id INT NOT NULL, attribute_id INT NOT NULL, value_option_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_540006F7CCFA12B8 ON candidate_attribute_value (profile_id)');
        $this->addSql('CREATE INDEX IDX_540006F7B6E62EFA ON candidate_attribute_value (attribute_id)');
        $this->addSql('CREATE INDEX IDX_540006F7E25618D9 ON candidate_attribute_value (value_option_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_candidate_attribute_value_profile ON candidate_attribute_value (profile_id, attribute_id)');
        $this->addSql('CREATE TABLE candidate_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, location VARCHAR(255) DEFAULT NULL, avatar_url VARCHAR(255) DEFAULT NULL, version INT DEFAULT 1 NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E8607AEA76ED395 ON candidate_profile (user_id)');
        $this->addSql('CREATE TABLE cv (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) DEFAULT \'DRAFT\' NOT NULL, is_visible BOOLEAN DEFAULT true NOT NULL, likes_count INT DEFAULT 0 NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, candidate_id INT NOT NULL, position_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B66FFE9291BD8781 ON cv (candidate_id)');
        $this->addSql('CREATE INDEX IDX_B66FFE92DD842E46 ON cv (position_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_candidate_position ON cv (candidate_id, position_id)');
        $this->addSql('CREATE TABLE cv_like (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cv_id INT NOT NULL, recruiter_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD2DA06FCFE419E2 ON cv_like (cv_id)');
        $this->addSql('CREATE INDEX IDX_CD2DA06F156BE243 ON cv_like (recruiter_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_cv_like_cv_recruiter ON cv_like (cv_id, recruiter_id)');
        $this->addSql('CREATE TABLE discussion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message_md TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, position_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C0B9F90FF675F31B ON discussion (author_id)');
        $this->addSql('CREATE INDEX idx_discussion_position ON discussion (position_id)');
        $this->addSql('CREATE TABLE oauth_identity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(50) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4AE96AD8A76ED395 ON oauth_identity (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_oauth_identity_provider ON oauth_identity (provider, provider_user_id)');
        $this->addSql('CREATE TABLE position (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(200) NOT NULL, short_description TEXT NOT NULL, company_name VARCHAR(255) DEFAULT NULL, level VARCHAR(100) DEFAULT NULL, is_public BOOLEAN DEFAULT false NOT NULL, max_projects INT DEFAULT 4 NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE position_access_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, operator VARCHAR(40) NOT NULL, rule_value VARCHAR(255) DEFAULT \'\' NOT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D97A8C6B6E62EFA ON position_access_rule (attribute_id)');
        $this->addSql('CREATE INDEX idx_position_access_rule_position ON position_access_rule (position_id)');
        $this->addSql('CREATE TABLE position_template_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_required BOOLEAN DEFAULT false NOT NULL, sort_order INT DEFAULT 0 NOT NULL, position_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CBE6163DB6E62EFA ON position_template_attribute (attribute_id)');
        $this->addSql('CREATE INDEX idx_position_template_attribute_position ON position_template_attribute (position_id)');
        $this->addSql('CREATE TABLE project (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(200) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, description_md TEXT NOT NULL, version INT DEFAULT 1 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, profile_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_project_profile ON project (profile_id)');
        $this->addSql('CREATE TABLE project_tag (project_id INT NOT NULL, tag_id INT NOT NULL, PRIMARY KEY (project_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_91F26D60166D1F9C ON project_tag (project_id)');
        $this->addSql('CREATE INDEX IDX_91F26D60BAD26311 ON project_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        // Functional index: tag names are unique case-insensitively (Doctrine cannot express this).
        $this->addSql('CREATE UNIQUE INDEX uniq_tag_name_lower ON tag (LOWER(name))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, is_blocked BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE user_recent_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, context VARCHAR(20) NOT NULL, last_used_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_80451FD2A76ED395 ON user_recent_attribute (user_id)');
        $this->addSql('CREATE INDEX IDX_80451FD2B6E62EFA ON user_recent_attribute (attribute_id)');
        $this->addSql('CREATE INDEX idx_user_recent_attribute_user_last_used ON user_recent_attribute (user_id, last_used_at)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE attribute_option ADD CONSTRAINT FK_78672EEAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_attribute_value ADD CONSTRAINT FK_540006F7CCFA12B8 FOREIGN KEY (profile_id) REFERENCES candidate_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_attribute_value ADD CONSTRAINT FK_540006F7B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_attribute_value ADD CONSTRAINT FK_540006F7E25618D9 FOREIGN KEY (value_option_id) REFERENCES attribute_option (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE candidate_profile ADD CONSTRAINT FK_E8607AEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_B66FFE9291BD8781 FOREIGN KEY (candidate_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv ADD CONSTRAINT FK_B66FFE92DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06FCFE419E2 FOREIGN KEY (cv_id) REFERENCES cv (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cv_like ADD CONSTRAINT FK_CD2DA06F156BE243 FOREIGN KEY (recruiter_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90FDD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE discussion ADD CONSTRAINT FK_C0B9F90FF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE oauth_identity ADD CONSTRAINT FK_4AE96AD8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6DD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_access_rule ADD CONSTRAINT FK_5D97A8C6B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_template_attribute ADD CONSTRAINT FK_CBE6163DDD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE position_template_attribute ADD CONSTRAINT FK_CBE6163DB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EECCFA12B8 FOREIGN KEY (profile_id) REFERENCES candidate_profile (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_tag ADD CONSTRAINT FK_91F26D60166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_tag ADD CONSTRAINT FK_91F26D60BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_recent_attribute ADD CONSTRAINT FK_80451FD2A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_recent_attribute ADD CONSTRAINT FK_80451FD2B6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_78672EEAB6E62EFA');
        $this->addSql('ALTER TABLE candidate_attribute_value DROP CONSTRAINT FK_540006F7CCFA12B8');
        $this->addSql('ALTER TABLE candidate_attribute_value DROP CONSTRAINT FK_540006F7B6E62EFA');
        $this->addSql('ALTER TABLE candidate_attribute_value DROP CONSTRAINT FK_540006F7E25618D9');
        $this->addSql('ALTER TABLE candidate_profile DROP CONSTRAINT FK_E8607AEA76ED395');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE9291BD8781');
        $this->addSql('ALTER TABLE cv DROP CONSTRAINT FK_B66FFE92DD842E46');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06FCFE419E2');
        $this->addSql('ALTER TABLE cv_like DROP CONSTRAINT FK_CD2DA06F156BE243');
        $this->addSql('ALTER TABLE discussion DROP CONSTRAINT FK_C0B9F90FDD842E46');
        $this->addSql('ALTER TABLE discussion DROP CONSTRAINT FK_C0B9F90FF675F31B');
        $this->addSql('ALTER TABLE oauth_identity DROP CONSTRAINT FK_4AE96AD8A76ED395');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6DD842E46');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6B6E62EFA');
        $this->addSql('ALTER TABLE position_template_attribute DROP CONSTRAINT FK_CBE6163DDD842E46');
        $this->addSql('ALTER TABLE position_template_attribute DROP CONSTRAINT FK_CBE6163DB6E62EFA');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EECCFA12B8');
        $this->addSql('ALTER TABLE project_tag DROP CONSTRAINT FK_91F26D60166D1F9C');
        $this->addSql('ALTER TABLE project_tag DROP CONSTRAINT FK_91F26D60BAD26311');
        $this->addSql('ALTER TABLE user_recent_attribute DROP CONSTRAINT FK_80451FD2A76ED395');
        $this->addSql('ALTER TABLE user_recent_attribute DROP CONSTRAINT FK_80451FD2B6E62EFA');
        $this->addSql('DROP TABLE attribute');
        $this->addSql('DROP TABLE attribute_option');
        $this->addSql('DROP TABLE candidate_attribute_value');
        $this->addSql('DROP TABLE candidate_profile');
        $this->addSql('DROP TABLE cv');
        $this->addSql('DROP TABLE cv_like');
        $this->addSql('DROP TABLE discussion');
        $this->addSql('DROP TABLE oauth_identity');
        $this->addSql('DROP TABLE position');
        $this->addSql('DROP TABLE position_access_rule');
        $this->addSql('DROP TABLE position_template_attribute');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_tag');
        $this->addSql('DROP INDEX uniq_tag_name_lower');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_recent_attribute');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
