<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 1/17: create user table
 */
final class Version20260901160001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE "user" (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email        VARCHAR(180)                         NOT NULL,
                password     VARCHAR(255)                         DEFAULT NULL,
                roles        JSON                                 NOT NULL,
                is_blocked   BOOLEAN                              DEFAULT FALSE NOT NULL,
                created_at   TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                PRIMARY KEY (id)
            )
        ');
        
        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE "user"');
    }
}
