<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 3/17: create attribute table
 */
final class Version20260901160003 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create attribute table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE attribute (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name         VARCHAR(100)                         NOT NULL,
                category     VARCHAR(40)                          NOT NULL,
                data_type    VARCHAR(40)                          NOT NULL,
                format       VARCHAR(40)                          DEFAULT NULL,
                description  TEXT                                 DEFAULT NULL,
                is_built_in  BOOLEAN                              DEFAULT FALSE NOT NULL,
                is_active    BOOLEAN                              DEFAULT TRUE  NOT NULL,
                created_at   TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_FA7AEFFB5E237E06 
            ON attribute (name)
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE attribute');
    }
}
