<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 6/17: create position table
 */
final class Version20260901160006 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create position table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE position (
                id                INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                title             VARCHAR(200)                         NOT NULL,
                short_description TEXT                                 NOT NULL,
                company_name      VARCHAR(255)                         DEFAULT NULL,
                level             VARCHAR(100)                         DEFAULT NULL,
                is_public         BOOLEAN                              DEFAULT FALSE NOT NULL,
                max_projects      INT                                  DEFAULT 4   NOT NULL,
                deleted_at        TIMESTAMP(0) WITHOUT TIME ZONE       DEFAULT NULL,
                version           INT                                  DEFAULT 1   NOT NULL,
                created_at        TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                PRIMARY KEY (id)
            )
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE position');
    }
}