<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 7/17: create position_access_rule table (depends on position, attribute)
 */
final class Version20260901160007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create position_access_rule table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE position_access_rule (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                operator     VARCHAR(40)                          NOT NULL,
                rule_value   VARCHAR(255)                         DEFAULT \'\' NOT NULL,
                position_id  INT                                  NOT NULL,
                attribute_id INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX IDX_5D97A8C6B6E62EFA 
            ON position_access_rule (attribute_id)
        ');

        $this->addSql('
            CREATE INDEX idx_position_access_rule_position 
            ON position_access_rule (position_id)
        ');

        $this->addSql('
            ALTER TABLE position_access_rule 
            ADD CONSTRAINT FK_5D97A8C6DD842E46 
            FOREIGN KEY (position_id) 
            REFERENCES position (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');

        $this->addSql('
            ALTER TABLE position_access_rule 
            ADD CONSTRAINT FK_5D97A8C6B6E62EFA 
            FOREIGN KEY (attribute_id) 
            REFERENCES attribute (id) 
            ON DELETE RESTRICT 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6DD842E46');
        $this->addSql('ALTER TABLE position_access_rule DROP CONSTRAINT FK_5D97A8C6B6E62EFA');
        $this->addSql('DROP TABLE position_access_rule');
    }
}