<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Replace the attribute.category enum string with a lookup-table FK
 * (attribute_category). Existing enum values are migrated row-by-row; the
 * table is seeded with the 6 canonical categories (idempotent).
 */
final class Version20260903074451 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Attribute category enum -> attribute_category lookup table';
    }

    public function up(Schema $schema): void
    {
        // 1. Lookup table + unique index (class-level ORM UniqueConstraint).
        $this->addSql('
            CREATE TABLE attribute_category (
                id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name VARCHAR(100)                         NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE UNIQUE INDEX uniq_attribute_category_name 
            ON attribute_category (name)
        ');

        // 2. Idempotent seed of the canonical categories.
        $this->addSql("
            INSERT INTO attribute_category (name) VALUES
                ('Certification'),
                ('Domain Knowledge'),
                ('Personal Information'),
                ('Soft Skills'),
                ('Technical Skills'),
                ('Languages')
            ON CONFLICT (name) DO NOTHING
        ");

        // 3. Nullable FK column first — the table is NOT empty.
        $this->addSql('
            ALTER TABLE attribute 
            ADD category_id INT DEFAULT NULL
        ');

        // 4. Map the legacy enum values onto the seeded lookup rows.
        $this->addSql("
            UPDATE attribute 
            SET category_id = c.id
            FROM attribute_category c
            WHERE c.name = CASE attribute.category
                WHEN 'CERTIFICATION'    THEN 'Certification'
                WHEN 'DOMAIN_KNOWLEDGE' THEN 'Domain Knowledge'
                WHEN 'PERSONAL_INFO'    THEN 'Personal Information'
                WHEN 'SOFT_SKILLS'      THEN 'Soft Skills'
            END
        ");

        // 5. Now safe to make it NOT NULL, drop the old column, add FK + index.
        $this->addSql('
            ALTER TABLE attribute 
            ALTER category_id SET NOT NULL
        ');

        $this->addSql('
            ALTER TABLE attribute 
            DROP category
        ');

        $this->addSql('
            ALTER TABLE attribute 
            ADD CONSTRAINT FK_FA7AEFFB12469DE2 
            FOREIGN KEY (category_id) 
            REFERENCES attribute_category (id) 
            ON DELETE RESTRICT 
            NOT DEFERRABLE
        ');

        $this->addSql('
            CREATE INDEX IDX_FA7AEFFB12469DE2 
            ON attribute (category_id)
        ');
    }

    public function down(Schema $schema): void
    {
        // (a) Refuse rollback when categories outside the original enum set
        // exist — they cannot be mapped back to a VARCHAR(40) enum column,
        // so aborting protects data integrity instead of silently losing rows.
        $orphans = $this->connection->fetchOne("
            SELECT COUNT(*) 
            FROM attribute_category 
            WHERE name NOT IN ('Certification', 'Domain Knowledge', 'Personal Information', 'Soft Skills')
        ");
        
        if ((int) $orphans > 0) {
            throw new \RuntimeException(
                'Cannot roll back: attribute_category contains rows outside the original 4 enum values. Remove them first.'
            );
        }

        $this->addSql('
            ALTER TABLE attribute 
            DROP CONSTRAINT FK_FA7AEFFB12469DE2
        ');

        $this->addSql('
            DROP INDEX IDX_FA7AEFFB12469DE2
        ');

        $this->addSql("
            ALTER TABLE attribute 
            ADD category VARCHAR(40)
        ");

        $this->addSql("
            UPDATE attribute 
            SET category = CASE c.name
                WHEN 'Certification'            THEN 'CERTIFICATION'
                WHEN 'Domain Knowledge'         THEN 'DOMAIN_KNOWLEDGE'
                WHEN 'Personal Information'     THEN 'PERSONAL_INFO'
                WHEN 'Soft Skills'              THEN 'SOFT_SKILLS'
            END
            FROM attribute_category c 
            WHERE c.id = attribute.category_id
        ");

        $this->addSql('
            ALTER TABLE attribute 
            ALTER category SET NOT NULL
        ');

        $this->addSql('
            ALTER TABLE attribute 
            DROP category_id
        ');

        $this->addSql('
            DROP TABLE attribute_category
        ');
    }
}