<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 8/17: create position_template_attribute table (depends on position, attribute)
 */
final class Version20260901160008 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create position_template_attribute table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE position_template_attribute (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                is_required  BOOLEAN                              DEFAULT FALSE NOT NULL,
                sort_order   INT                                  DEFAULT 0   NOT NULL,
                position_id  INT                                  NOT NULL,
                attribute_id INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX IDX_CBE6163DB6E62EFA 
            ON position_template_attribute (attribute_id)
        ');

        $this->addSql('
            CREATE INDEX idx_position_template_attribute_position 
            ON position_template_attribute (position_id)
        ');

        $this->addSql('
            ALTER TABLE position_template_attribute 
            ADD CONSTRAINT FK_CBE6163DDD842E46 
            FOREIGN KEY (position_id) 
            REFERENCES position (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');

        $this->addSql('
            ALTER TABLE position_template_attribute 
            ADD CONSTRAINT FK_CBE6163DB6E62EFA 
            FOREIGN KEY (attribute_id) 
            REFERENCES attribute (id) 
            ON DELETE RESTRICT 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE position_template_attribute DROP CONSTRAINT FK_CBE6163DDD842E46');
        $this->addSql('ALTER TABLE position_template_attribute DROP CONSTRAINT FK_CBE6163DB6E62EFA');
        $this->addSql('DROP TABLE position_template_attribute');
    }
}