<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 14/17: create project table (depends on candidate_profile)
 */
final class Version20260901160014 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create project table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE project (
                id            INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                name          VARCHAR(200)                         NOT NULL,
                start_date    TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                end_date      TIMESTAMP(0) WITHOUT TIME ZONE       DEFAULT NULL,
                description_md TEXT                                 NOT NULL,
                version       INT                                  DEFAULT 1 NOT NULL,
                created_at    TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                profile_id    INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX idx_project_profile 
            ON project (profile_id)
        ');

        $this->addSql('
            ALTER TABLE project 
            ADD CONSTRAINT FK_2FB3D0EECCFA12B8 
            FOREIGN KEY (profile_id) 
            REFERENCES candidate_profile (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EECCFA12B8');
        $this->addSql('DROP TABLE project');
    }
}