<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 16/17: create user_recent_attribute table (depends on user, attribute)
 */
final class Version20260901160016 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_recent_attribute table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE user_recent_attribute (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                context      VARCHAR(20)                          NOT NULL,
                last_used_at TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                user_id      INT                                  NOT NULL,
                attribute_id INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX IDX_80451FD2A76ED395 
            ON user_recent_attribute (user_id)
        ');

        $this->addSql('
            CREATE INDEX IDX_80451FD2B6E62EFA 
            ON user_recent_attribute (attribute_id)
        ');

        $this->addSql('
            CREATE INDEX idx_user_recent_attribute_user_last_used 
            ON user_recent_attribute (user_id, last_used_at)
        ');

        $this->addSql('
            ALTER TABLE user_recent_attribute 
            ADD CONSTRAINT FK_80451FD2A76ED395 
            FOREIGN KEY (user_id) 
            REFERENCES "user" (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');

        $this->addSql('
            ALTER TABLE user_recent_attribute 
            ADD CONSTRAINT FK_80451FD2B6E62EFA 
            FOREIGN KEY (attribute_id) 
            REFERENCES attribute (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_recent_attribute DROP CONSTRAINT FK_80451FD2A76ED395');
        $this->addSql('ALTER TABLE user_recent_attribute DROP CONSTRAINT FK_80451FD2B6E62EFA');
        $this->addSql('DROP TABLE user_recent_attribute');
    }
}