<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 2/17: create candidate_profile table (depends on user)
 */
final class Version20260901160002 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create candidate_profile table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE candidate_profile (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                first_name   VARCHAR(100)                         NOT NULL,
                last_name    VARCHAR(100)                         NOT NULL,
                location     VARCHAR(255)                         DEFAULT NULL,
                avatar_url   VARCHAR(255)                         DEFAULT NULL,
                version      INT                                  DEFAULT 1 NOT NULL,
                updated_at   TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                user_id      INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE UNIQUE INDEX UNIQ_E8607AEA76ED395 
            ON candidate_profile (user_id)
        ');

        $this->addSql('
            ALTER TABLE candidate_profile 
            ADD CONSTRAINT FK_E8607AEA76ED395 
            FOREIGN KEY (user_id) 
            REFERENCES "user" (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE candidate_profile DROP CONSTRAINT FK_E8607AEA76ED395');
        $this->addSql('DROP TABLE candidate_profile');
    }
}
