<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 13/17: create oauth_identity table (depends on user)
 */
final class Version20260901160013 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create oauth_identity table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE oauth_identity (
                id              INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                provider        VARCHAR(50)                          NOT NULL,
                provider_user_id VARCHAR(255)                        NOT NULL,
                created_at      TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                user_id         INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX IDX_4AE96AD8A76ED395 
            ON oauth_identity (user_id)
        ');

        $this->addSql('
            CREATE UNIQUE INDEX uniq_oauth_identity_provider 
            ON oauth_identity (provider, provider_user_id)
        ');

        $this->addSql('
            ALTER TABLE oauth_identity 
            ADD CONSTRAINT FK_4AE96AD8A76ED395 
            FOREIGN KEY (user_id) 
            REFERENCES "user" (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE oauth_identity DROP CONSTRAINT FK_4AE96AD8A76ED395');
        $this->addSql('DROP TABLE oauth_identity');
    }
}