<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 12/17: create discussion table (depends on position, user)
 */
final class Version20260901160012 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create discussion table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE discussion (
                id          INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                message_md  TEXT                                 NOT NULL,
                created_at  TIMESTAMP(0) WITHOUT TIME ZONE       NOT NULL,
                position_id INT                                  NOT NULL,
                author_id   INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX IDX_C0B9F90FF675F31B 
            ON discussion (author_id)
        ');

        $this->addSql('
            CREATE INDEX idx_discussion_position 
            ON discussion (position_id)
        ');

        $this->addSql('
            ALTER TABLE discussion 
            ADD CONSTRAINT FK_C0B9F90FDD842E46 
            FOREIGN KEY (position_id) 
            REFERENCES position (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');

        $this->addSql('
            ALTER TABLE discussion 
            ADD CONSTRAINT FK_C0B9F90FF675F31B 
            FOREIGN KEY (author_id) 
            REFERENCES "user" (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE discussion DROP CONSTRAINT FK_C0B9F90FDD842E46');
        $this->addSql('ALTER TABLE discussion DROP CONSTRAINT FK_C0B9F90FF675F31B');
        $this->addSql('DROP TABLE discussion');
    }
}