<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration 4/17: create attribute_option table (depends on attribute)
 */
final class Version20260901160004 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create attribute_option table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('
            CREATE TABLE attribute_option (
                id           INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                label        VARCHAR(255)                         NOT NULL,
                value        VARCHAR(255)                         NOT NULL,
                sort_order   INT                                  DEFAULT 0 NOT NULL,
                attribute_id INT                                  NOT NULL,
                PRIMARY KEY (id)
            )
        ');

        $this->addSql('
            CREATE INDEX idx_attribute_option_attribute 
            ON attribute_option (attribute_id)
        ');

        $this->addSql('
            ALTER TABLE attribute_option 
            ADD CONSTRAINT FK_78672EEAB6E62EFA 
            FOREIGN KEY (attribute_id) 
            REFERENCES attribute (id) 
            ON DELETE CASCADE 
            NOT DEFERRABLE
        ');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE attribute_option DROP CONSTRAINT FK_78672EEAB6E62EFA');
        $this->addSql('DROP TABLE attribute_option');
    }
}
